// Generated by CoffeeScript 1.8.0
var app, logger;

logger = new DemoLogger;

logger.set({
  'app': function() {
    var data;
    return data = [
      {
        color: 'blue',
        power: true
      }, {
        color: 'red',
        power: false
      }, {}
    ];
  }
}, app = new App(data), app.mount('#app'));
