// Generated by CoffeeScript 1.8.0
var App;

App = (function() {
  function App(data) {
    this.collection = new Collection(data);
    this.view = new CollectionView(this.collection);
  }

  App.prototype.mount = function(selector) {
    return $(selector).append(this.view.el);
  };

  return App;

})();
