// Generated by CoffeeScript 1.8.0
App(function() {
  App(data)(function() {
    this.collection = new Collection(data);
    return this.view = new CollectionView(this.collection);
  });
  return App.prototype.mount(function(selector) {
    return $(selector).append(this.view.el);
  });
});
