// Generated by CoffeeScript 1.8.0
var Colletion;

Colletion = (function() {
  function Colletion() {
    this.data = data;
    this.models = [];
    this._initilize;
  }

  Colletion.prototype._initilize = function() {
    return this.data.forEach((function(_this) {
      return function(src, index) {
        var model;
        model = new Model(src);
        model.id = index;
        return _this.models.push(model);
      };
    })(this));
  };

  Colletion.prototype.allON = function() {
    return this.models.forEach(function(model) {
      return model.power = true;
    });
  };

  Colletion.prototype.allOFF = function() {
    return this.models.forEach(function(model) {
      return model.power = false;
    });
  };

  return Colletion;

})();
