// Generated by CoffeeScript 1.8.0
var CollectionView;

CollectionView = (function() {
  function CollectionView(collection) {
    this.collection = collection;
    this.el = $('<div>');
    this.render();
    this._eventify();
  }

  CollectionView.prototype._eventify = function() {
    return this.el.on('click:switch', (function(_this) {
      return function(e, model) {
        return _this.update(model.id);
      };
    })(this));
  };

  CollectionView.prototype.render = function() {
    var $frag, $off, $on;
    this.views = [];
    $frag = $(document.createDocumentFragment());
    this.collection.models.forEach((function(_this) {
      return function(model, index) {
        _this.views.push(modelView);
        return $frag.append(modelView.el);
      };
    })(this));
    this.el.html($frag);
    $on = $('<button>ON</button>').on('click')((function(_this) {
      return function() {
        _this.collection.allON();
        return _this.updateAll();
      };
    })(this));
    $off = $('<button>OFF</button>').on('click')((function(_this) {
      return function() {
        _this.collection.allOFF();
        return _this.updateAll();
      };
    })(this));
    return this.el.append($on, $off);
  };

  CollectionView.prototype.update = function() {
    return this.views[index].update();
  };

  CollectionView.prototype.updateAll = function() {
    return this.views.forEach(function(modelView) {
      return modelView.update();
    });
  };

  return CollectionView;

})();
