// Generated by CoffeeScript 1.8.0
var Model;

Model = (function() {
  function Model(opt) {
    this.power = !!opt.power;
    this.color = opt.color || "yellow";
  }

  Model.prototype.on = function() {
    return this.power = true;
  };

  Model.prototype.off = function() {
    return this.power = false;
  };

  Model.prototype.toggle = function() {
    if (this.power) {
      if (this.on()) {
        return this.off();
      }
    }
  };

  return Model;

})();
