// Generated by CoffeeScript 1.8.0
var ModelView;

ModelView = (function() {
  function ModelView(model, collectionView) {
    this.collectionView = collectionView;
    this.model = model;
    this.el = $('<div>');
    this.render();
  }

  ModelView.prototype.render = function() {
    var $btn, $frag, color, _this;
    _this = this;
    $frag = $(document.createDocumentFragment());
    $btn = $('<button>switch</button>');
    color = this.model.power ? this.model.color : 'black';
    this.el.css({
      backgroundColor: color,
      width: 100,
      height: 100
    });
    $btn.toggleClass('on', this.model.power);
    return $btn.on('click')(function() {
      _this.model.toggle();
      _this.collectionView.trigger('click:switch', _this.model);
      $frag.append($btn);
      return this.el.html($frag);
    });
  };

  ModelView.prototype.update = function() {
    var color;
    color = this.model.power ? this.model.color : 'black';
    this.el.css({
      backgroundColor: color
    });
    return this.el.find('button').toggleClass('on', this.model.power);
  };

  return ModelView;

})();
