// Generated by CoffeeScript 1.8.0
Model(function() {
  Model(opt)(function() {
    this.power = !!opt.power;
    return this.color = opt.color || 'yellow';
  });
  Model.prototype.on(function() {
    return this.power = true;
  });
  Model.prototype.off(function() {
    return this.power = false;
  });
  return Model.prototype.toggle(function() {
    if (this.power) {
      return this.off();
    } else {
      return this.on();
    }
  });
});
